version: 2.1
orbs:
  aws-serverless: circleci/aws-serverless@1.0.2
jobs:
  build_app:
    executor: aws-serverless/default
    steps:
      - checkout
      - aws-serverless/install
      - run: sam build
      - run: sam deploy --debug --confirm-changeset
workflows:
  my-workflow:
    jobs:
      - build_app